### ISSUE TITLE
import bsv from "bsv" ^^^^^^  SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by combstraight** [synfonaut/hummingbird#1]
I get the following error when I attempt to run `require("hummingbird-bitcoin")` through node.

**Comment by synfonaut** [comment]
Can you let me know which version of Node you're using? I've been developing on a pretty recent version but can look to providing a compiled version that supports older versions.

**Comment by combstraight** [comment]
Sure, I am currently using Node 12.13.1.

**Comment by synfonaut** [comment]
I think this is because I'm using "node -r esm <script>" which allows all of the latest features from node. I have made a note to generate a bundle so this isn't needed anymore.

**Comment by synfonaut** [comment]
This should be fixed in the latest version `hummingbird-bitcoin@0.0.7`, please let me know if you're still seeing this error!
